import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider"
import AdSense from "@/components/adsense/AdSense";
import Footer from "@/components/footer/Footer";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  url: new URL("https://datanalytics-biz.onrender.com"),
  keywords: [],
  title: {
    default: "Data Analytics Blogs",
    template: "%s | Data Analytics Blogs"
  },
  openGraph:{
    description: "Generated by create next app",
    images: ["https://images.pexels.com/photos/2061168/pexels-photo-2061168.jpeg?auto=compress&cs=tinysrgb&w=600"]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-p-20 scroll-smooth">
      <head>
      <AdSense pId="ca-pub-4700602838719113"/>
      </head>
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
        <Navbar/>

        <div className="min-h-screen">
        {children}
        </div>
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
